#!/bin/bash

devname="donuts-are-good"
projectpath="$HOME/Projects"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <project name>"
  exit 1
fi

name="$1"
dir="$projectpath/$name"

mkdir -p "$dir"

# Create main.go
cat > "$dir/main.go" << EOF
package main

func main() {
	println("alive!")
}
EOF

# Create README.md
cat > "$dir/README.md" << EOF
# $name

## usage

## license

MIT License 2023 donuts-are-good, for more info see license.md
EOF

# Create LICENSE.md
cat > "$dir/LICENSE.md" << EOF
MIT License
Copyright (c) 2023 donuts-are-good
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF

# Create .gitignore
cat > "$dir/.gitignore" << EOF
.DS_Store
.Trash-1000
$name
BUILDS
EOF

# Initialize Go modules
(
  cd "$dir" || exit
  go mod init "github.com/$devname/$name"
  go mod tidy
)

# Initialize Git repository
(
  cd "$dir" || exit
  git init
  git remote add origin "https://github.com/$devname/$name.git"
  git add -A
)

# Open project in Visual Studio Code
code "$dir"
